<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.views.ChangePasswordTest" tests="3" time="0.002">
	<testcase classname="django.contrib.auth.tests.views.ChangePasswordTest" name="test_password_change_fails_with_invalid_old_password" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.ChangePasswordTest" name="test_password_change_fails_with_mismatched_passwords" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.ChangePasswordTest" name="test_password_change_succeeds" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
