<?xml version="1.0" ?>
<testsuite errors="0" failures="0" name="django.contrib.auth.tests.views.LoginTest" tests="2" time="0.002">
	<testcase classname="django.contrib.auth.tests.views.LoginTest" name="test_current_site_in_context_after_login" time="0.001"/>
	<testcase classname="django.contrib.auth.tests.views.LoginTest" name="test_security_check" time="0.001"/>
	<system-out/>
	<system-err/>
</testsuite>
